Repository looker-open-source/components, pull requests merged in 2021-06, with the labels that each got.

#2461 chore: Move Lerna to independent mode
  lerna.json
Labels: 2.0

#2447 fix(MultiFunctionButton): Properly set width of smaller button, properly hide in-active button from screen-readers
  packages/components/src/Button/MultiFunctionButton.story.tsx
  packages/components/src/Button/MultiFunctionButton.tsx
  packages/components/src/Layout/Semantics/Layout/Layout.story.tsx
  snapshots/CopyToClipboard/Basic-snap.png
  snapshots/Layout/Basic-snap.png
  snapshots/Layout/Fixed With Footer And Header Shadow-snap.png
  snapshots/MultiFunctionButton/Component Size-snap.png
  snapshots/MultiFunctionButton/Copy To Clipboard-snap.png
Labels: 2.0, bug

#2462 fix(Tree): Fix border alignment
  packages/components/src/Tree/utils/generateTreeBorder.ts
Labels: 2.0, bug

#2202 fix: use DOMRect in lieu of ClientRect
  packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
  packages/components/src/utils/useGlobalHotkeys.ts
  packages/components/src/utils/useMeasuredElement.ts
Labels: 2.0

#2458 chore(deps): Update caniuse
  package.json
  yarn.lock
Labels: 2.0

#2464 fix(useTooltip): Don't include `aria-describedby` on target when Tooltip disabled
  packages/components/src/Button/IconButton.tsx
  packages/components/src/Tooltip/types.ts
  packages/components/src/Tooltip/useTooltip.tsx
Labels: 2.0, bug

#2496 fix(Tooltip): Don't included spurious `undefined` className on disable Tooltip target
  packages/components/src/Tooltip/Tooltip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/Tooltip/useTooltip.tsx
Labels: 2.0

#2497 fix(DialogHeader): Restore previous behavior for DialogHeader detail property
  packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.story.tsx
  packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
  packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.tsx
Labels: 2.0

#2499 fix(DialogHeader): Properly emit `aria-label` to DOM
  packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
  packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.tsx
Labels: 2.0

#2495 fix: Include @types/styled-system in devDependencies to simplify installation
  packages/components/package.json
  www/src/documentation/develop/index.mdx
Labels: 2.0

#2512 fix(HoverDisclosure): Remove strategy prop, add placeholderWidth
  packages/components/src/List/ListItem.test.tsx
  packages/components/src/List/ListItem.tsx
  packages/components/src/List/types.ts
  packages/components/src/List/utils/getDetailOptions.ts
  packages/components/src/Tree/Tree.test.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/stories/FieldItem.tsx
  packages/components/src/utils/HoverDisclosure/HoverDisclosure.tsx
Labels: 2.0, cla: yes

#2510 fix(HoverDisclosure): Remove strategy prop, add placeholderWidth
  packages/components/src/List/ListItem.test.tsx
  packages/components/src/List/ListItem.tsx
  packages/components/src/List/types.ts
  packages/components/src/List/utils/getDetailOptions.ts
  packages/components/src/Tree/Tree.test.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/stories/FieldItem.tsx
  packages/components/src/utils/HoverDisclosure/HoverDisclosure.tsx
Labels: 1.4, cla: yes

#2513 chore: Update resolutions to update vulnerable transient dependencies
  package.json
  packages/visualizations-nivo/package.json
  packages/visualizations-table/package.json
  packages/visualizations-visx/package.json
  packages/visualizations/package.json
  yarn.lock
Labels: 2.0, cla: yes

#2525 chore: CHANGELOG v2.0.0
  CHANGELOG.md
Labels: 2.0, cla: yes

#2514 fix: Correct web site publishing to work with lerna independent versioning
  config/website-latest.sh
Labels: 2.0, cla: yes

#2494 fix(CardContent): Properly absorb padding (pN) values
  packages/components/src/Card/CardContent.tsx
  packages/design-tokens/src/utils/index.ts
  packages/design-tokens/src/utils/paddingDefaultsHelper.test.ts
  packages/design-tokens/src/utils/paddingDefaultsHelper.ts
Labels: 2.1, cla: yes

#2528 fix(DialogLayout): `footerSecondary` is only valid if `footer` is also specified
  packages/components/src/Dialog/Layout/DialogLayout.story.tsx
  packages/components/src/Dialog/Layout/DialogLayout.test.tsx
  packages/components/src/Dialog/Layout/DialogLayout.tsx
Labels: cla: yes

#2530 fix(PopoverContent): changed default horizontal padding from `p="small"` to `pb="medium" pt="xsmall" px="large"`
  packages/components/src/Popover/Layout/PopoverContent/PopoverContent.story.tsx
  packages/components/src/Popover/Layout/PopoverContent/PopoverContent.test.tsx
  packages/components/src/Popover/Layout/PopoverContent/PopoverContent.tsx
  snapshots/PopoverContent/Custom Padding-snap.png
  snapshots/PopoverLayout/Basic-snap.png
  snapshots/PopoverLayout/Full-snap.png
  snapshots/PopoverLayout/Header Hide Heading-snap.png
  snapshots/PopoverLayout/Header-snap.png
Labels: cla: yes

#2532 chore: Update yarn.lock
  yarn.lock
Labels: cla: yes

#2531 chore: Move playground into apps folder
  .gitignore
  README.md
  apps/playground/CHANGELOG.md
  apps/playground/README.md
  apps/playground/babel.config.js
  apps/playground/package.json
  apps/playground/src/index.tsx
  apps/playground/src/template.html
  apps/playground/tsconfig.json
  apps/playground/webpack.config.js
  package.json
  packages/components/README.md
  playground/tsconfig.json
  tsconfig.json
  www/src/documentation/develop/data-fetching.mdx
  yarn.lock
Labels: cla: yes

#2534 chore(deps): Update browserslist & host-git-info to get upstream patches
  package.json
  yarn.lock
Labels: cla: yes

#2542 chore: Update yarn.lock
  yarn.lock
Labels: cla: yes

#2541 fix(FontFaceLoader): Memoize font-import to prevent font-loading flash
  apps/playground/package.json
  apps/playground/src/index.tsx
  packages/components-providers/src/FontFaceLoader/FontFaceLoader.test.tsx
  packages/components-providers/src/FontFaceLoader/FontFaceLoader.tsx
Labels: cla: yes

#2549 fix(ModalHeader): Lint errors in test file
  packages/components/src/Modal/ModalHeader/ModalHeader.test.tsx
Labels: cla: yes

#2553 chore(lint): Disable prettier in oss-compat
  packages/eslint-config/oss-compat.js
Labels: cla: yes

#2552 chore(deps): bump @looker/sdk from 21.6.0 to 21.8.0
  package.json
  yarn.lock
Labels: cla: yes

#2550 fix(FieldInline): Adjust description line height and padding for `FieldCheckbox`, `FieldRadio`, and `FieldToggleSwitch`
  packages/components/src/Form/Fields/FieldInline.tsx
  snapshots/FieldCheckbox/Detail Description Error-snap.png
  snapshots/FieldCheckbox/Detail Description-snap.png
  snapshots/FieldRadio/Detail Description Error-snap.png
  snapshots/FieldRadio/Detail Description-snap.png
  snapshots/FieldToggleSwitch/Detail Description Error-snap.png
  snapshots/FieldToggleSwitch/Detail Description-snap.png
  storybook/package.json
Labels: cla: yes

#2556 fix: Restore CI code coverage reporting
  .github/workflows/ci.yml
  jest.config.js
Labels: cla: yes
