Repository looker-open-source/components, pull requests merged in 2021-05, with the labels that each got.

#2281 feat(Accordion): Toggle on spacebar key
  packages/components/src/Accordion/Accordion.tsx
  packages/components/src/Accordion/AccordionDisclosure.tsx
  packages/components/src/Tree/Tree.tsx
  packages/components/src/Tree/types.ts
Labels: next

#2277 feat: useFocusVisible hook
  packages/components/src/Accordion/Accordion.story.tsx
  packages/components/src/Accordion/AccordionDisclosure.tsx
  packages/components/src/Button/Button.story.tsx
  packages/components/src/Button/ButtonBase.tsx
  packages/components/src/Button/ButtonGroup.story.tsx
  packages/components/src/Button/ButtonItem.tsx
  packages/components/src/Button/ButtonToggle.story.tsx
  packages/components/src/Button/IconButton.story.tsx
  packages/components/src/Button/iconButtonColor.ts
  packages/components/src/Chip/Chip.story.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/DataTable/Column/DataTableCell.test.tsx
  packages/components/src/DataTable/Column/DataTableCell.tsx
  packages/components/src/DataTable/Column/FocusableCell.tsx
  packages/components/src/DataTable/stories/Interaction.tsx
  packages/components/src/List/List.story.tsx
  packages/components/src/List/ListItem.tsx
  packages/components/src/Tabs/Tab.tsx
  packages/components/src/Tabs/Tabs.story.tsx
  packages/components/src/utils/index.ts
  packages/components/src/utils/useClickable.ts
  packages/components/src/utils/useFocusVisible.test.tsx
  packages/components/src/utils/useFocusVisible.ts
  snapshots/Accordion/Focused-snap.png
  snapshots/Button/Critical Focused-snap.png
  snapshots/Button/Focused-snap.png
  snapshots/Button/Neutral Focused-snap.png
  snapshots/ButtonGroup/Focused-snap.png
  snapshots/ButtonToggle/Focused-snap.png
  snapshots/Chip/Focused-snap.png
  snapshots/DataTable/Focused-snap.png
  snapshots/IconButton/Toggle Color Focused-snap.png
  snapshots/List/Focused-snap.png
  snapshots/Tabs/Focused-snap.png
  storybook/.storybook/manager-head.html
Labels: next

#2338 fix(NavList): Properly style Trees within NavList
  packages/components/src/Form/Inputs/Select/SelectOptions.tsx
  packages/components/src/Icon/IconPlaceholder.tsx
  packages/components/src/List/ListItemLayout.tsx
  packages/components/src/List/ListItemLayoutAccessory.tsx
  packages/components/src/List/ListItemWrapper.tsx
  packages/components/src/NavList/NavList.story.tsx
  packages/components/src/NavList/NavList.test.tsx
  packages/components/src/NavList/NavList.tsx
  packages/components/src/NavList/index.ts
  packages/components/src/Tree/Tree.tsx
  packages/components/src/Tree/TreeStyle.tsx
  snapshots/NavList/Basic-snap.png
  snapshots/NavList/Mixed Navigation-snap.png
  snapshots/NavList/Nav List Example-snap.png
Labels: 1.2

#2403 feat(Truncate): now supports an optional `description` property
  packages/components/src/List/ListItem.tsx
  packages/components/src/NavList/NavList.story.tsx
  packages/components/src/Truncate/Truncate.test.tsx
  packages/components/src/Truncate/Truncate.tsx
  snapshots/NavList/Basic-snap.png
Labels: next

#2300 feat(Layout): Supports displaying shadow when content overflows container height
  packages/components/src/Layout/Semantics/Aside.tsx
  packages/components/src/Layout/Semantics/Header.tsx
  packages/components/src/Layout/Semantics/Layout.tsx
  packages/components/src/Layout/Semantics/Section.tsx
  packages/components/src/Layout/Semantics/Semantics.test.tsx
  packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
  packages/components/src/utils/index.ts
  packages/components/src/utils/useOverflow.ts
  snapshots/Layout/Fixed-snap.png
  snapshots/Layout/Footer Header Shadow-snap.png
  snapshots/Layout/Multiple Layouts-snap.png
Labels: next

#2420 feat!: Remove theme.reset
  packages/components/src/Layout/utils/simple.ts
  packages/design-tokens/src/system/reset.test.tsx
  packages/design-tokens/src/system/reset.ts
  packages/design-tokens/src/theme/theme.ts
Labels: 2.0

#2419 feat!: Remove support for keyColor on List, Tree & Menu (use color="key")
  packages/components/src/List/List.test.tsx
  packages/components/src/List/List.tsx
  packages/components/src/List/ListItem.story.tsx
  packages/components/src/List/ListItem.test.tsx
  packages/components/src/List/ListItem.tsx
  packages/components/src/List/types.ts
  packages/components/src/Menu/MenuItem.tsx
  packages/components/src/Menu/MenuList.tsx
  packages/components/src/NavList/NavList.test.tsx
  packages/components/src/NavList/NavList.tsx
  packages/components/src/Tree/Tree.test.tsx
  packages/components/src/Tree/Tree.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/TreeItem.tsx
  packages/components/src/Tree/types.ts
  www/src/documentation/components/content/demos/ListItemPropTable.tsx
  www/src/documentation/components/content/tree.mdx
Labels: 2.0

#2421 feat!: Remove GlobalStyle placeholder & ie11support flag (ie11 now works without)
  packages/components-providers/src/ComponentsProvider.tsx
  packages/design-tokens/src/GlobalStyle/GlobalStyle.tsx
  packages/design-tokens/src/GlobalStyle/index.ts
  packages/design-tokens/src/index.ts
Labels: 2.0

#2418 feat!: Removing color aliases (secondary & subdued)
  packages/components-date/src/InputDate/InputDate.story.tsx
  packages/components-theme-editor/src/Examples/Dashboard.tsx
  packages/components/src/Breakpoint/Breakpoint.story.tsx
  packages/components/src/DataTable/BulkActions/BulkActions.tsx
  packages/components/src/DataTable/Column/DataTableCell.tsx
  packages/components/src/DataTable/Table.tsx
  packages/components/src/Form/Inputs/Select/SelectOptions.tsx
  packages/components/src/Menu/Menu.story.tsx
  packages/components/src/Text/Heading.story.tsx
  packages/components/src/Text/Heading.test.tsx
  packages/design-tokens/src/color/colors.ts
  packages/design-tokens/src/color/types/aliases.ts
  packages/design-tokens/src/color/types/index.ts
  packages/design-tokens/src/color/utils/generateColorAliases.ts
  packages/design-tokens/src/color/utils/generateColors.ts
  packages/design-tokens/src/theme/utils/generateTheme.test.ts
  snapshots/Colors/All Colors-snap.png
  www/src/Layout/Documentation.tsx
  www/src/components/Navigation/Section.tsx
  www/src/documentation/components/content/card.mdx
  www/src/documentation/components/date/input-date-range.mdx
  www/src/documentation/components/date/input-date.mdx
  www/src/documentation/components/date/input-time-select.mdx
  www/src/documentation/components/forms/inline-input-text.mdx
  www/src/documentation/components/layout/demos/BoxSpacingRecipeTable.tsx
  www/src/documentation/components/text/headings.mdx
  www/src/documentation/components/text/span.mdx
  www/src/documentation/develop/extending.mdx
Labels: 2.0

#2426 fix(ListItem): Removed background transition
  packages/components/src/List/ListItemLabel.tsx
  packages/components/src/Tree/stories/FieldItem.tsx
  packages/components/src/Tree/stories/FieldPicker.story.tsx
Labels: 1.4, 2.0

#2429 fix(ListItem): Removed background transition
  packages/components/src/List/ListItemLabel.tsx
  packages/components/src/Tree/stories/FieldItem.tsx
  packages/components/src/Tree/stories/FieldPicker.story.tsx
Labels: 1.4
