Repository looker-open-source/components, pull requests merged in 2021-08, with the labels that each got.

#2678 test(Badge): testing prop defaults
  packages/components/src/Badge/Badge.test.tsx
Labels: cla: yes

#2680 test(Layout): Add coverage
  packages/components/src/Layout/Semantics/Layout/Layout.test.tsx
Labels: cla: yes

#2688 test(useI18n): improve coverage
  packages/components-providers/src/I18n/useI18n.test.tsx
Labels: cla: yes

#2679 test(useScrollLock): improve coverage
  packages/components/src/utils/useScrollLock.test.tsx
Labels: cla: yes

#2683 test(DataTable): Utilities Test Coverage
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/Item/DataTableItem.tsx
  packages/components/src/DataTable/Item/DataTableRow.tsx
  packages/components/src/DataTable/utils/__snapshots__/sort_utils.test.ts.snap
  packages/components/src/DataTable/utils/allItemsSelected.ts
  packages/components/src/DataTable/utils/sort_utils.test.ts
  packages/components/src/DataTable/utils/useSelectManager.test.tsx
  packages/components/src/DataTable/utils/useSelectManager.tsx
Labels: cla: yes

#2691 test(AvatarCombo): Disable screenshot due to jitter
  packages/components/src/Avatar/AvatarCombo.story.tsx
  snapshots/AvatarCombo/Primary-snap.png
Labels: cla: yes

#2689 test(Accordion): Add coverage
  packages/components/src/Accordion/Accordion.test.tsx
Labels: cla: yes

#2686 test(ModalLayout-ModalHeader-ModalFooter): add covarege
  packages/components/src/Modal/ModalFooter/ModalFooter.test.tsx
  packages/components/src/Modal/ModalHeader/ModalHeader.test.tsx
  packages/components/src/Modal/ModalLayout/ModalLayout.test.tsx
Labels: cla: yes

#2694 chore: yarn deduplicate
  apps/filter-demo/package.json
  www/package.json
  yarn.lock
Labels: cla: yes

#2695 test(Modal): updated for better test coverage
  packages/components/src/Modal/modal.test.tsx
Labels: cla: yes

#2611 fix(Panel): Avoid focusing elements underneath
  packages/components/src/Panel/Panel.story.tsx
  packages/components/src/Panel/Panel.test.tsx
  packages/components/src/Panel/PanelSurface.tsx
  packages/components/src/Panel/Panels.tsx
  packages/components/src/Panel/usePanel.tsx
  packages/components/src/utils/index.ts
  packages/components/src/utils/useAnimationState.ts
Labels: cla: yes, 2.1

#2697 fix(Tooltip): Reduce re-renders to improve performance
  apps/playground/src/index.tsx
  packages/components/src/Button/IconButton.tsx
  packages/components/src/Tooltip/Tooltip.story.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/Tooltip/types.ts
  packages/components/src/Tooltip/useTooltip.tsx
Labels: cla: yes

#2676 feat(NavTree): Added indicator toggle only behavior
  packages/components/src/NavList/NavList.tsx
  packages/components/src/NavTree/NavTree.story.tsx
  packages/components/src/NavTree/NavTree.test.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/NavTree/NavTreeDisclosure.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  packages/components/src/NavTree/NavTreeItemContent.tsx
  packages/components/src/NavTree/types.ts
  snapshots/NavTree/Basic-snap.png
  snapshots/NavTree/Link-snap.png
Labels: cla: yes

#2711 fix(Text): Clarify behavior, mark as deprecated and recommend `Span` instead
  packages/components/src/Text/Span.tsx
  packages/components/src/Text/Text.tsx
Labels: cla: yes

#2702 fix(InputFilters): Should support placeholder attribute
  packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
  packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
  packages/components/src/Form/Inputs/InputFilters/types.ts
Labels: cla: yes

#2712 feat(NavTree): Added left padding to indicator icon to improve click targeting
  packages/components/src/NavList/NavList.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  snapshots/NavList/Basic-snap.png
  snapshots/NavList/Mixed Navigation-snap.png
  snapshots/NavTree/Basic-snap.png
  snapshots/NavTree/Link-snap.png
  snapshots/NavTree/Parent Icon-snap.png
Labels: cla: yes

#2714 fix(VisuallyHidden): Position causing whitespace issue with Page in Chrome
  packages/components/src/Layout/Semantics/Layout/Layout.story.tsx
  packages/components/src/VisuallyHidden/VisuallyHidden.test.tsx
  packages/components/src/VisuallyHidden/VisuallyHidden.tsx
Labels: cla: yes

#2715 fix(ButtonToggle): Remove background color for focus via click
  packages/components/src/Button/ButtonItem.tsx
  packages/components/src/Button/ButtonSet.tsx
  packages/components/src/Button/ButtonToggle.story.tsx
Labels: cla: yes

#2684 test: Introduce @storybook/testing-react
  jest.setup.js
  package.json
  packages/components-date/src/FieldDate/FieldDate.story.tsx
  packages/components/package.json
  packages/components/src/Dialog/Layout/DialogLayout.test.tsx
  packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.test.tsx
  packages/components/src/Modal/ModalLayout/ModalLayout.tsx
  packages/components/src/Popover/Layout/PopoverLayout.story.tsx
  packages/components/src/Popover/Layout/PopoverLayout.test.tsx
  packages/filter-components/src/Filter/Filter.stories.tsx
  storybook/.storybook/componentsDecorator.tsx
  yarn.lock
Labels: cla: yes

#2723 feat: Leverage new theme.elevations instead of theme.shadows
  packages/components/src/Card/Card.test.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/Dialog/DialogSurface.tsx
  packages/components/src/Drawer/DrawerSurface.tsx
  packages/components/src/Form/Inputs/InputColor/Handle/Handle.tsx
  packages/components/src/Menu/NestedMenuSurface.ts
  packages/components/src/Overlay/OverlaySurface.tsx
  packages/design-tokens/src/colors.story.tsx
  snapshots/Breakpoint/Desktop UI-snap.png
  snapshots/Breakpoint/Mobile UI-snap.png
  snapshots/Breakpoint/Tablet UI-snap.png
  snapshots/Card/Raised-snap.png
  snapshots/Colors/All Colors-snap.png
  snapshots/Design Tokens / Colors/All Colors-snap.png
  snapshots/Dialog/Height-snap.png
  snapshots/Dialog/Long Content-snap.png
  snapshots/Dialog/Medium Content-snap.png
  snapshots/Dialog/Open-snap.png
  snapshots/Dialog/Placement Cover-snap.png
  snapshots/Dialog/Placement Top-snap.png
Labels: cla: yes, 2.2

#2727 fix: Replace usage of t-shirt size space with units
  packages/components-theme-editor/package.json
  packages/components-theme-editor/src/Examples/Charts/Bar.tsx
  packages/components-theme-editor/src/Examples/ColorSwatches.tsx
  packages/components-theme-editor/src/ThemeEditorForm.tsx
  storybook/package.json
  www/package.json
  www/src/components/HeaderContent/HeaderContent.tsx
  yarn.lock
Labels: cla: yes

#2728 refactor(density): Consolidate default density in theme
  packages/components/src/Accordion/Accordion.tsx
  packages/components/src/Accordion2/Accordion2.tsx
  packages/components/src/List/List.tsx
  packages/components/src/ListItem/ListItemIcon.tsx
  packages/components/src/ListItem/ListItemLabel.tsx
  packages/components/src/ListItem/utils/createListItemPartitions.tsx
  packages/components/src/ListItem/utils/listItemDimensions.ts
  packages/components/src/Menu/MenuHeading.tsx
  packages/components/src/Menu/MenuItem.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  packages/components/src/Tree/utils/generateIndent.ts
  packages/design-tokens/src/theme/theme.ts
Labels: cla: yes

#2730 docs: typo `componentn` in Span documentation
  www/src/documentation/components/text/span.mdx
Labels: cla: yes

#2732 refactor: Ripple effect
  packages/components/src/Ripple/Ripple.story.tsx
  packages/components/src/Ripple/rippleStyle.ts
  packages/components/src/Ripple/types.ts
  packages/components/src/Ripple/useRipple.test.tsx
  packages/components/src/Ripple/useRipple.tsx
Labels: cla: yes

#2733 docs: Fix a few small issues with spacing docs
  www/src/documentation/foundations/demos/SpacingOptionsTable.tsx
  www/src/documentation/foundations/spacing.mdx
Labels: cla: yes

#2735 fix(Elevation): add elevation level of plus0 to match spec
  packages/design-tokens/src/elevation/index.ts
  packages/design-tokens/src/elevation/types.ts
  www/src/documentation/foundations/demos/ElevationList.tsx
  www/src/documentation/foundations/elevation.mdx
Labels: cla: yes

#2736 fix(NavTree): Made sure NavTree had role="treeitem"
  packages/components/src/NavTree/NavTree.test.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/NavTree/index.ts
  packages/components/src/Tree/Tree.tsx
Labels: cla: yes

#2745 chore: Nix setup
  .envrc
  .gitignore
  shell.nix
Labels: cla: yes

#2746 chore(Filter Demo): support lookml dashboards, longer dashboard list
  apps/filter-demo/src/DashboardEmbed.tsx
  apps/filter-demo/src/DashboardList.tsx
  apps/filter-demo/src/FilterDemo.tsx
Labels: cla: yes

#2747 chore: CHANGELOG clean-ups
  CHANGELOG.md
  packages/components/CHANGELOG.md
  packages/design-tokens/CHANGELOG.md
Labels: cla: yes

#2751 fix(TreeItem): Fixed bad link props dispersion bug on TreeItem
  packages/components/src/NavTree/NavTree.story.tsx
  packages/components/src/NavTree/NavTreeItem.test.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/TreeItem.tsx
Labels: cla: yes

#2750 fix(TreeItem): Link-related prop dispersion bug
  packages/components/src/NavTree/NavTree.story.tsx
  packages/components/src/NavTree/NavTreeItem.test.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/TreeItem.tsx
Labels: cla: yes

#2749 refactor(Tabs2): Implementation clean-ups
  packages/components/src/Tabs2/Tab2.tsx
  packages/components/src/Tabs2/Tabs2.story.tsx
  packages/components/src/Tabs2/Tabs2.test.tsx
  packages/components/src/Tabs2/Tabs2.tsx
  packages/components/src/Tabs2/types.ts
  snapshots/Tabs2/Disabled-snap.png
  www/src/documentation/components/content/tabs.mdx
Labels: cla: yes

#2721 feat(IconButton): Add ripple effect
  packages/components/src/Button/ButtonBase.tsx
  packages/components/src/Button/IconButton.story.tsx
  packages/components/src/Button/IconButton.test.tsx
  packages/components/src/Button/IconButton.tsx
  packages/components/src/Button/iconButtonOutline.ts
  packages/components/src/Ripple/Ripple.story.tsx
  packages/components/src/Ripple/rippleStyle.ts
  packages/components/src/Ripple/useRipple.test.tsx
  packages/components/src/Ripple/useRipple.tsx
  packages/design-tokens/src/theme/theme.ts
  snapshots/IconButton/Toggle Color Focused-snap.png
Labels: next, cla: yes

#2753 feat: Rename @looker/eslint-config to @looker/eslint-config-oss
  .eslintrc.js
  packages/eslint-config-oss/CHANGELOG.md
  packages/eslint-config-oss/README.md
  packages/eslint-config-oss/index.js
  packages/eslint-config-oss/license-header.js
  packages/eslint-config-oss/oss-compat.js
  packages/eslint-config-oss/package.json
  packages/eslint-config-oss/src/.keep
  packages/eslint-config-oss/tsconfig.build.json
  www/package.json
  yarn.lock
Labels: cla: yes

#2759 feat(List): Added dual axis keyboard navigation
  packages/components/src/List/List.spec.tsx
  packages/components/src/List/List.story.tsx
  packages/components/src/List/List.tsx
  packages/components/src/List/utils/getNextItemFocus.ts
  packages/components/src/List/utils/index.ts
  packages/components/src/Menu/Menu.story.tsx
  packages/components/src/Menu/MenuList.tsx
  packages/components/src/Menu/useNestedMenu.tsx
  packages/components/src/NavList/NavList.spec.tsx
  packages/components/src/NavList/stories/NavList.story.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/Tree/TreeCollection.tsx
  packages/components/src/Tree/utils/index.ts
  packages/components/src/utils/useArrowKeyNav.ts
Labels: cla: yes

#2754 feat(SelectMulti & InputChips): Support value formatting
  packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
  packages/components/src/Form/Inputs/InputChips/InputChips.spec.tsx
  packages/components/src/Form/Inputs/InputChips/InputChips.story.tsx
  packages/components/src/Form/Inputs/InputChips/InputChips.tsx
  packages/components/src/Form/Inputs/Select/SelectMulti.spec.tsx
  packages/components/src/Form/Inputs/Select/SelectMulti.tsx
  packages/components/src/Form/Inputs/Select/stories/SelectMulti.story.tsx
  www/src/documentation/components/forms/input-chips.mdx
  www/src/documentation/components/forms/select-multi.mdx
Labels: cla: yes

#2764 fix(PopoverContent): Properly absorb `p` value (also `DialogContent`)
  packages/components/src/Dialog/Layout/DialogContent/DialogContent.spec.tsx
  packages/components/src/Dialog/Layout/DialogContent/DialogContent.tsx
  packages/components/src/Popover/Layout/PopoverContent/PopoverContent.spec.tsx
  packages/components/src/Popover/Layout/PopoverContent/PopoverContent.tsx
Labels: cla: yes

#2766 docs: Consistently leverage units (u*) across .mdx files
  www/src/documentation/components/actions/button-group.mdx
  www/src/documentation/components/actions/pagination.mdx
  www/src/documentation/components/content/accordion.mdx
  www/src/documentation/components/content/breakpoint.mdx
  www/src/documentation/components/content/chip.mdx
  www/src/documentation/components/content/data-table.mdx
  www/src/documentation/components/content/divider.mdx
  www/src/documentation/components/content/icon.mdx
  www/src/documentation/components/content/list.mdx
  www/src/documentation/components/content/message-bar.mdx
  www/src/documentation/components/content/tabs.mdx
  www/src/documentation/components/date/input-date-range.mdx
  www/src/documentation/components/date/input-date.mdx
  www/src/documentation/components/date/input-time-select.mdx
  www/src/documentation/components/dialogs/dialog-content.mdx
  www/src/documentation/components/forms/checkbox-group.mdx
  www/src/documentation/components/forms/checkbox.mdx
  www/src/documentation/components/forms/inline-text-area.mdx
  www/src/documentation/components/forms/radio-group.mdx
  www/src/documentation/components/layout/flex.mdx
  www/src/documentation/components/layout/grid.mdx
  www/src/documentation/components/layout/panel.mdx
  www/src/documentation/components/overlays/menu.mdx
  www/src/documentation/components/overlays/popover.mdx
  www/src/documentation/components/overlays/popovercontent.mdx
  www/src/documentation/foundations/borders.mdx
  www/src/documentation/foundations/breakpoints.mdx
Labels: cla: yes

#2755 feat: Update filter packages
  apps/filter-demo/package.json
  package.json
  packages/filter-components/package.json
  packages/filter-components/src/DashboardFilter/DashboardFilter.spec.tsx
  packages/filter-components/src/DashboardFilter/use_suggestable.ts
  packages/filter-components/src/Filter/Filter.spec.tsx
  packages/filter-components/src/Filter/Filter.stories.tsx
  packages/filter-components/src/Filter/Filter.tsx
  packages/filter-components/src/Filter/components/AdvancedFilter/components/DateFilter/utils/relative_timeframe_conversions.ts
  packages/filter-components/src/Filter/components/ControlFilter/ControlFilter.tsx
  packages/filter-components/src/Filter/components/ControlFilter/components/Slider/RangeSlider.stories.tsx
  packages/filter-components/src/Filter/components/ControlFilter/components/TagList/TagList.spec.tsx
  packages/filter-components/src/Filter/components/ControlFilter/components/TagList/TagList.stories.tsx
  packages/filter-components/src/Filter/types/filter_props.ts
  packages/filter-components/src/Filter/utils/can_render_filter.spec.ts
  packages/filter-components/src/Filter/utils/can_render_filter.ts
  packages/filter-components/src/Filter/utils/control_filter_utils.spec.ts
  packages/filter-components/src/Filter/utils/control_filter_utils.ts
  packages/filter-components/src/Filter/utils/get_filter_token_item.spec.ts
  packages/filter-components/src/Filter/utils/get_filter_token_item.ts
  packages/filter-components/src/Filter/utils/index.ts
  packages/filter-components/src/Filter/utils/use_filter_config.ts
  packages/filter-components/src/Filter/utils/use_option_filtering.ts
  packages/filter-expressions/package.json
  packages/filter-expressions/src/grammars/__snapshots__/string_grammar.spec.ts.snap
  packages/filter-expressions/src/grammars/string_grammar.ts
  packages/filter-expressions/src/grammars/string_grammar_test_expressions.ts
  packages/filter-expressions/src/utils/get_matches_advanced_node.ts
  packages/filter-expressions/src/utils/index.ts
  packages/filter-expressions/src/utils/string/escape_leading_and_trailing_whitespaces.spec.ts
  packages/filter-expressions/src/utils/string/escape_leading_and_trailing_whitespaces.ts
  packages/filter-expressions/src/utils/string/escape_with_caret.spec.ts
  packages/filter-expressions/src/utils/string/escape_with_caret.ts
  packages/filter-expressions/src/utils/string/string_filter_to_string.ts
  snapshots/Filters / Filter/Config-snap.png
  yarn.lock
Labels: cla: yes

#2767 docs: Fix a few more units
  www/src/documentation/components/actions/button-toggle.mdx
  www/src/documentation/components/dialogs/dialog-footer.mdx
  www/src/documentation/components/fields/field.mdx
  www/src/documentation/components/forms/input-chips.mdx
  www/src/documentation/components/layout/grid.mdx
  www/src/documentation/components/layout/space.mdx
Labels: cla: yes

#2765 fix(SelectOptions): remove Checkbox component
  packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
  packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
Labels: cla: yes

#2774 refactor(NavTree): Removed style override for padding-right
  packages/components/src/NavList/stories/LeftNav.story.tsx
  packages/components/src/NavTree/NavTree.tsx
  snapshots/NavList/Left Nav-snap.png
Labels: cla: yes

#2770 fix(IconButton): Make hover/focus background consistent with shape
  packages/components/src/Button/IconButton.spec.tsx
  packages/components/src/Button/IconButton.story.tsx
  packages/components/src/Button/IconButton.tsx
  packages/components/src/Button/iconButtonTypes.ts
  packages/components/src/LkFieldTree/stories/FieldPickerItem.tsx
  packages/components/src/Pagination/Pagination.tsx
  snapshots/IconButton/Square-snap.png
  www/src/documentation/components/actions/icon-button.mdx
Labels: cla: yes

#2772 fix(IconButton): IconButton should not shrink within a flex container
  packages/components/src/Button/IconButton.tsx
  snapshots/FieldChips/Truncate-snap.png
Labels: cla: yes

#2769 refactor: Consistent structure properties in styled-components interpolation blocks
  packages/components-date/src/InputTime/InputTime.tsx
  packages/components/src/Button/ButtonItem.tsx
  packages/components/src/Button/ButtonTransparent.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/DataTable/BulkActions/BulkActions.tsx
  packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
  packages/components/src/DataTable/Item/DataTableRow.tsx
  packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
  packages/components/src/Form/Inputs/InlineTextArea/InlineTextArea.tsx
  packages/components/src/Form/Inputs/InputColor/Swatch/Swatch.tsx
  packages/components/src/Form/Inputs/InputText/InputText.tsx
  packages/components/src/Form/Inputs/Radio/Radio.tsx
  packages/components/src/Form/Inputs/TextArea/TextArea.tsx
  packages/components/src/Form/Inputs/innerInputStyle.ts
  packages/components/src/Form/ValidationMessage/ValidationMessage.tsx
  packages/components/src/ProgressCircular/DeterminateProgress.tsx
  packages/components/src/ProgressCircular/ProgressSvg.tsx
  packages/components/src/Spinner/Spinner.tsx
  packages/components/src/Table/TableCell/tableCell.ts
  packages/components/src/Tabs2/TabList2.tsx
  packages/components/src/utils/useFocusVisible.ts
  packages/design-tokens/src/elevation/index.ts
  www/src/MDX/Link.tsx
  www/src/components/DocTable.tsx
  www/src/documentation/components/layout/demos/BoxSpacingRecipeTable.tsx
  www/src/documentation/develop/theme.mdx
  www/src/documentation/foundations/breakpoints.mdx
  www/src/documentation/foundations/demos/ColorBlendsGrid.tsx
  www/src/documentation/foundations/demos/ElevationList.tsx
Labels: cla: yes

#2785 fix(useAccordion2): Ignore changes to defaultOpen
  packages/components/src/Accordion2/Accordion2.spec.tsx
  packages/components/src/Accordion2/useAccordion2.tsx
Labels: cla: yes

#2784 fix(NavTree): Various NavTree fixes
  packages/components/src/Accordion2/AccordionIndicator.tsx
  packages/components/src/Accordion2/types.ts
  packages/components/src/NavList/stories/LeftNav.story.tsx
  packages/components/src/NavTree/NavTree.spec.tsx
  packages/components/src/NavTree/NavTree.story.tsx
  packages/components/src/NavTree/NavTree.tsx
  packages/components/src/NavTree/NavTreeItem.tsx
  packages/components/src/NavTree/types.ts
  packages/components/src/Tree/utils/indicatorDefaults.tsx
  snapshots/NavTree/Focused Basic-snap.png
  snapshots/NavTree/Focused Link-snap.png
Labels: cla: yes

#2776 feat(Radio): add ripple effect
  packages/components/src/Form/Inputs/Radio/Radio.spec.tsx
  packages/components/src/Form/Inputs/Radio/Radio.story.tsx
  packages/components/src/Form/Inputs/Radio/Radio.tsx
  snapshots/FieldRadio/Basic-snap.png
  snapshots/FieldRadio/Checked-snap.png
  snapshots/FieldRadio/Detail Description Error-snap.png
  snapshots/FieldRadio/Detail Description-snap.png
  snapshots/FieldRadio/Disabled Checked-snap.png
  snapshots/FieldRadio/Disabled-snap.png
  snapshots/FieldRadio/Error-snap.png
  snapshots/FieldRadioGroup/Basic-snap.png
  snapshots/FieldRadioGroup/Disabled-snap.png
  snapshots/FieldRadioGroup/Error Inline-snap.png
  snapshots/FieldRadioGroup/Error-snap.png
  snapshots/FieldRadioGroup/Inline-snap.png
  snapshots/FieldRadioGroup/Required-snap.png
  snapshots/Radio/Basic-snap.png
  snapshots/Radio/Checked-snap.png
  snapshots/Radio/Disabled Checked-snap.png
  snapshots/Radio/Disabled-snap.png
Labels: cla: yes
