Repository looker-open-source/components, pull requests merged in 2021-04, with the labels that each got.

#2186 feat(Layout): scroll use cases
  packages/components/snapshots/Layout/Scroll All Areas-snap.png
  packages/components/snapshots/Layout/Scroll Independently Default-snap.png
  packages/components/snapshots/Layout/Scroll Selected Areas-snap.png
  packages/components/src/Layout/Semantics/Aside.tsx
  packages/components/src/Layout/Semantics/Header.tsx
  packages/components/src/Layout/Semantics/Section.tsx
  packages/components/src/Layout/Semantics/Semantics.test.tsx
  packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
Labels: enhancement

#2189 fix(TreeItem): Clicks on padding trigger onClick when parent Tree labelBackgroundColor is true
  .github/workflows/ci.yml
  packages/components/src/List/ListItem.tsx
  packages/components/src/Tree/TreeItem.test.tsx
  packages/components/src/Tree/TreeItem.tsx
  packages/components/src/Tree/stories/FieldPicker.story.tsx
Labels: bug

#2199 feat(Accordion): Refactored Accordion interface and composition
  packages/components/src/Accordion/Accordion.story.tsx
  packages/components/src/Accordion/Accordion.test.tsx
  packages/components/src/Accordion/Accordion.tsx
  packages/components/src/Accordion/AccordionContent.tsx
  packages/components/src/Accordion/AccordionContext.tsx
  packages/components/src/Accordion/AccordionDisclosure.tsx
  packages/components/src/Accordion/AccordionDisclosureLayout.tsx
  packages/components/src/Accordion/index.ts
  packages/components/src/Accordion/types.ts
  packages/components/src/Form/Fieldset/Fieldset.tsx
  packages/components/src/Tree/Tree.tsx
  packages/components/src/Tree/types.ts
  snapshots/Accordion/Basic-snap.png
  snapshots/Accordion/Legacy Composition-snap.png
  www/src/components/Navigation/Section.tsx
  www/src/documentation/components/content/accordion.mdx
  www/src/documentation/components/content/list.mdx
Labels: enhancement

#2216 feat(List): support fontFamily as prop
  packages/components/src/List/List.story.tsx
  packages/components/src/List/List.tsx
  snapshots/List/Font Family-snap.png
  www/src/documentation/components/content/list.mdx
Labels: enhancement

#2239 chore(deps): Update testing-library & (most) webpack dependencies
  package.json
  packages/components-providers/package.json
  packages/components-test-utils/package.json
  packages/components/package.json
  packages/components/src/Breakpoint/Breakpoint.story.tsx
  packages/components/src/Form/Inputs/InputSearch/InputSearch.test.tsx
  packages/components/src/Form/Inputs/InputText/InputText.test.tsx
  packages/design-tokens/package.json
  playground/package.json
  snapshots/Breakpoint/Mobile UI-snap.png
  storybook/src/setup/storyshotsConfig.ts
  www/package.json
  yarn.lock
Labels: dependencies

#2244 chore(deps): Babel dependency updates
  package.json
  packages/components/package.json
  packages/design-tokens/package.json
  playground/package.json
  storybook/package.json
  www/package.json
  yarn.lock
Labels: dependencies

#2247 chore: Fix typescript-eslint dependency version and related lint breakages
  package.json
  packages/components-providers/src/TrapStack/TrapStackProvider.tsx
  packages/components-providers/src/TrapStack/types.ts
  packages/components-providers/src/TrapStack/utils.ts
  packages/components/src/Avatar/Avatar.test.tsx
  packages/components/src/Avatar/AvatarCombo.story.tsx
  packages/components/src/Avatar/AvatarUser.story.tsx
  packages/components/src/Avatar/AvatarUser.tsx
  packages/components/src/Calendar/Calendar.tsx
  packages/components/src/DataTable/stories/useSortManager.tsx
  packages/components/src/Form/Fields/FieldText/FieldText.story.tsx
  packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
  packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
  packages/components/src/List/ListDivider.tsx
  packages/components/src/Menu/MenuHeading.hooks.ts
  packages/components/src/Panel/Panel.test.tsx
  packages/components/src/Panel/Panel.tsx
  packages/components/src/utils/useTrapStack.ts
  packages/design-tokens/src/system/reset.test.tsx
  packages/eslint-config/index.js
  www/src/MDX/Li.tsx
  www/src/MDX/Ol.tsx
  www/src/MDX/Paragraph.tsx
  www/src/MDX/Ul.tsx
  yarn.lock
Labels: dependencies
